### ISSUE TITLE
Dashboard does not show which coordinators can activate oneself

### ISSUE THREAD

**Issue by laurenzfg** [studieren-ohne-grenzen/dashboard-web-frontend#8]
But the dashboard says the _following coordinators_
![Screenshot_2020-10-21 Mein Profil - SOG Vogelnest](https://user-images.githubusercontent.com/7126826/96779806-d0218780-13ec-11eb-8c36-dd963d442232.png)

**Comment by wanLo** [comment]
Actually, this is fully implemented in the frontend with the request to `api/inactive_info` (store/user.js line 231). Problem might be in the backend instead?

**Comment by laurenzfg** [comment]
fixed.
